CodeSamples/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from Codesample import views
from django.contrib.auth import views
from Codesample import forms
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('Codesample.urls', namespace='blog')), 

]

Codesample/urls.py
from django.conf.urls import url, include, patterns
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views
from django.contrib.auth.forms import AuthenticationForm
# from views import myPosts, postit, profile, show, update, register, publish, allPosts,home
from views import profile, register, home, login_user, publish, allposts, likeit, myPosts, edit
from forms import LoginForm

app_name = "CodeSample"
urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^logout/$', views.logout, {'next_page': '/login'}, name='logout'),
    # url(r'^postit/$', postit, name='posting'),
    # url(r'^update/(?P<id>[0-9]+)/$', update, name='update'),
    # url(r'^show/(?P<id>[0-9]+)/$', show, name='show'),
    url(r'^accounts/profile/$', profile, name='profile'),
    # url(r'^login/$', 'django.contrib.auth.views.login'),  # If user is not login it will redirect to login page
    url(r'^login/$', login_user,
        name='login'),
    url(r'^register/$', register, name='registeration'),
    url(r'^publish/$', publish, name='publish'),
    url(r'^allposts/$', allposts, name='allposts'),
    url(r'^likeit/$', likeit, name='likeit'),
    url(r'^myposts/$', myPosts, name='myposts'),
    url(r'^edit/$', edit, name='edit'),
]

urlpatterns += patterns('',
                        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                            'document_root': settings.MEDIA_ROOT}))

templates/home.html
{% extends 'site_base.html' %}
{% block LeftNav %}
    <li><a id="home" href="#">Home</a></li>
    <li><a id="posts" href="#">MyPosts</a></li>
    <li><a id="update" href="#">Update</a></li>
{% endblock %}


{% block RightNav %}
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ user }}
            <span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
            <li><a href="/">Home</a></li>
            <li><a id="profile" href="#">Profile</a></li>
            <li class="divider"></li>
            <li><a href="/logout"><span class="glyphicon glyphicon-log-out"></span> &nbsp;&nbsp;Logout</a></li>
        </ul>
    </li>
{% endblock %}
{% block content %}
    <div id="thecontent" class="container">
    </div>
    <script>

    function deletefoto(fotoid,postid,modelid) {

        x=$("input[id^='updating']").val()
    console.log($("input[id^='updating']").val())
        $.ajax({
                url: '/edit/',
                type: 'POST',
                data: {
                    operation:'delete',
                    name: $("input[id^='updating']").val(),
                    id:fotoid

                },
                beforeSend: function (xhr, settings) {
                    if (settings.type == 'POST' || settings.type == 'PUT' || settings.type == 'DELETE') {

                        if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                            // Only send the token to relative URLs i.e. locally.
                            xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                        }
                    }
                },
                dataType: 'text',
                contentType: 'application/x-www-form-urlencoded',
                success: function (data, textStatus, jQxhr) {

                    //resp = JSON.parse(data);
                    console.log(data);
                    if (data=='OK') {
                        $('.modal.in').modal('hide');
                        $(postid).remove();
                    }

                },
                error: function (jqXhr, textStatus, errorThrown) {
                    console.log(errorThrown);
                }
            });


    }
    function editfoto(fotoid,postnameid) {
    console.log($("input[id^='updating']").val())

        $.ajax({
                url: '/edit/',
                type: 'POST',
                data: {
                    operation:'edit',
                    name: '',
                    id:fotoid

                },
                beforeSend: function (xhr, settings) {
                    if (settings.type == 'POST' || settings.type == 'PUT' || settings.type == 'DELETE') {

                        if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                            // Only send the token to relative URLs i.e. locally.
                            xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                        }
                    }
                },
                dataType: 'text',
                contentType: 'application/x-www-form-urlencoded',
                success: function (data, textStatus, jQxhr) {

                    //resp = JSON.parse(data);
                    console.log(data);
                    if (data=='EDITED') {
                        $('.modal.in').modal('hide');
                        $(postnameid).text($("input[id^='updating']").val());

                    }

                },
                error: function (jqXhr, textStatus, errorThrown) {
                    console.log(errorThrown);
                }
            });


    }

        function likeit(fotoid) {
            console.log('LIKED')
            {#    #}
            {#     $('#like').tooltip({ items: "#like", content: "Thank you!!!"});#}
            {#    $('#like').tooltip("open");#}
            {#    $('#like').onmouseout(function () {#}
            {#        $('#like').tooltip("disable");#}
            {#    });#}

            $.ajax({
                url: '/likeit/',
                type: 'POST',
                data: {fotoid},
                beforeSend: function (xhr, settings) {
                    if (settings.type == 'POST' || settings.type == 'PUT' || settings.type == 'DELETE') {

                        if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                            // Only send the token to relative URLs i.e. locally.
                            xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                        }
                    }
                },
                dataType: 'text',
                contentType: 'application/x-www-form-urlencoded',
                success: function (data, textStatus, jQxhr) {

                    //resp = JSON.parse(data);
                    console.log(data);
                    $('#likess'+fotoid).text(data);
                },
                error: function (jqXhr, textStatus, errorThrown) {
                    console.log(errorThrown);
                }
            });


        }
        $(document).ready(function () {

            $.ajax({
                url: '/allposts/',
                type: 'POST',
                data: {},
                beforeSend: function (xhr, settings) {
                    if (settings.type == 'POST' || settings.type == 'PUT' || settings.type == 'DELETE') {

                        if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                            // Only send the token to relative URLs i.e. locally.
                            xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                        }
                    }
                },
                dataType: 'text',
                contentType: 'application/x-www-form-urlencoded',
                success: function (data, textStatus, jQxhr) {
                    console.log("Hi");
                    //resp = JSON.parse(data);
                    console.log(data);
                    console.log(getCookie('csrftoken'))
                    $("#thecontent").html(data);
                },
                error: function (jqXhr, textStatus, errorThrown) {
                    console.log(errorThrown);
                }
            });


            $("#home").click(function () {

                $.ajax({
                    url: '/allposts/',
                    type: 'POST',
                    data: {},
                    beforeSend: function (xhr, settings) {
                        if (settings.type == 'POST' || settings.type == 'PUT' || settings.type == 'DELETE') {

                            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                                // Only send the token to relative URLs i.e. locally.
                                xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                            }
                        }
                    },
                    dataType: 'text',
                    contentType: 'application/x-www-form-urlencoded',
                    success: function (data, textStatus, jQxhr) {
                        console.log("Hi");
                        //resp = JSON.parse(data);
                        console.log(data);
                        console.log(getCookie('csrftoken'))
                        $("#thecontent").html(data);
                    },
                    error: function (jqXhr, textStatus, errorThrown) {
                        console.log(errorThrown);
                    }
                });

            });


            $("#profile").click(function () {

                $.ajax({
                    url: '/accounts/profile/',
                    type: 'POST',
                    data: {},
                    beforeSend: function (xhr, settings) {
                        if (settings.type == 'POST' || settings.type == 'PUT' || settings.type == 'DELETE') {

                            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                                // Only send the token to relative URLs i.e. locally.
                                xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                            }
                        }
                    },
                    dataType: 'text',
                    contentType: 'application/x-www-form-urlencoded',
                    success: function (data, textStatus, jQxhr) {
                        console.log("Hi");
                        //resp = JSON.parse(data);
{#                        console.log(data);#}
{#                        console.log(getCookie('csrftoken'))#}
                        $("#thecontent").html(data);
                    },
                    error: function (jqXhr, textStatus, errorThrown) {
                        console.log(errorThrown);
                    }
                });

            });



            $("#update").click(function () {
                $.ajax({
                    url: '/publish/',
                    type: 'POST',
                    data: {},
                    beforeSend: function (xhr, settings) {
                        if (settings.type == 'POST' || settings.type == 'PUT' || settings.type == 'DELETE') {

                            if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                                // Only send the token to relative URLs i.e. locally.
                                xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                            }
                        }
                    },
                    dataType: 'text',
                    contentType: 'application/x-www-form-urlencoded',
                    success: function (data, textStatus, jQxhr) {
                        console.log("Hi");
                        //resp = JSON.parse(data);
                        console.log(data);
                        console.log(getCookie('csrftoken'))
                        $("#thecontent").html(data);
                    },
                    error: function (jqXhr, textStatus, errorThrown) {
                        console.log(errorThrown);
                    }
                });
            });
        });
        $("#posts").click(function () {
            $.ajax({
                url: '/myposts/',
                type: 'POST',
                data: {},
                beforeSend: function (xhr, settings) {
                    if (settings.type == 'POST' || settings.type == 'PUT' || settings.type == 'DELETE') {

                        if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
                            // Only send the token to relative URLs i.e. locally.
                            xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
                        }
                    }
                },
                dataType: 'text',
                contentType: 'application/x-www-form-urlencoded',
                success: function (data, textStatus, jQxhr) {
                    console.log("Hi");
                    //resp = JSON.parse(data);
                    console.log(data);
                    {#                        console.log(getCookie('csrftoken'))#}
                    $("#thecontent").html(data);
                },
                error: function (jqXhr, textStatus, errorThrown) {
                    console.log(errorThrown);
                }
            });
        });


        function getCookie(cname) {
            var name = cname + "=";
            var ca = document.cookie.split(';');
            for (var i = 0; i < ca.length; i++) {
                var c = ca[i];
                while (c.charAt(0) == ' ') {
                    c = c.substring(1);
                }
                if (c.indexOf(name) == 0) {
                    return c.substring(name.length, c.length);
                }
            }
            return "";
        }
    </script>
{% endblock %}

templates/login.html
{% extends 'site_base.html' %}
{% block RightNav %}
    <li><a href="{% url 'blog:registeration' %}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
{% endblock %}
{% block content %}
{% if message %}
   <div class="alert alert-danger"> <p>{{ message }}</p></div>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
        <div class="alert alert-warning"> <p>Please Login First</p></div>
    {% else %}
        <div class="alert alert-info"> <p>Please login First</p></div>
    {% endif %}
{% endif %}

<form method="post" action="">

    {% csrf_token %}


    <h2>Login</h2>

    <div class="form-group">

      <input type="text" class="form-control" name="{{ form.email.name }}" id="usr" placeholder="Email" />
    </div>
    <div class="form-group">

      <input type="password" name="{{ form.password.name }}" placeholder="Password" class="form-control" id="pwd"/>
    </div>
      <div class="form-group">
      <input class="btn btn-primary" type="submit" value="login"/>
    </div>
<input type="hidden" name="next" value="{{ next }}"/>
</form>

{% endblock %}

templates/post.html
<html>
<body>


{% if post %}
    <p>
{#    <input type="hidden" name="id" value="{{ post.id }}" />#}
    {{ post.title }} <br />
    {{ post.text }}
    <br />
        <a href="{% url 'blog:update' post.id %}">Edit</a>

    </p>
    {% else %}
    {{ Sorry }}

{% endif %}

</body>
</html>

templates/posts.html
<div class="container" style="align-content: center;">

    {% for post in posts %}

  <div id="post{{ post.id }}">

            <h3 id="namee{{ post.id }}">
        {{ post.name }}</h3>
            <i id="author{{ post.id }}"><span style="font-size: 10px; padding: 0px">Posted by</span> {{ post.author }}</i><br>
            <span style="font-size: 8px; color: #737373">at {{ post.date }}</span>
            {% if post.author == user %}
{#           <button onclick="edit({{ post.id }},{{ post.name }})">Edit</button>#}
                <a data-toggle="modal" href="#mymodal{{ post.id }}">Edit</a>
        {% endif %}


            <img class="img-responsive" src= "{{ post.foto.url }}" alt="{{ post.foto }}" />
        <br>
        <button style="background-color: Transparent;border: none;" class="omg glyphicon glyphicon-thumbs-up" onclick="likeit('{{ post.id }}')"> <span id="likess{{ post.id }}" data-toggle="tooltip" title="Like">{{ post.likes }}</span></button>&nbsp;&nbsp;&nbsp;&nbsp;
{#        <a href="#"> <span class="glyphicon glyphicon-comment" data-toggle="tooltip" title="Comment"></span></a>#}
                <hr class="divider" style="width: 40%;">

        <div class="modal fade" id="mymodal{{ post.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h4 class="modal-title">Edit Post</h4>
        </div>
        <div class="modal-body">
                <input id="updating" type="text" class="form-control" placeholder="{{ post.name }}" required/>
            or<br>
            <input type="button" class="btn btn-danger" value="Delete" onclick="deletefoto({{ post.id }},'#post{{ post.id }}','#mymodal{{ post.id }}')" />

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary" onclick="editfoto({{ post.id }},'#namee{{ post.id }}')">Save changes</button>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
</div>
    {% endfor %}


 <!-- Button trigger modal -->
{#  <a data-toggle="modal" href="#myModal1" class="btn btn-primary btn-lg">Launch demo modal</a>#}

  <!-- Modal -->
{#  <div class="modal fade" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">#}
{#    <div class="modal-dialog">#}
{#      <div class="modal-content">#}
{#        <div class="modal-header">#}
{#          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>#}
{#          <h4 class="modal-title">Edit Post</h4>#}
{#        </div>#}
{#        <div class="modal-body">#}
{#          #}
{#        </div>#}
{#        <div class="modal-footer">#}
{#          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>#}
{#          <button type="button" class="btn btn-primary">Save changes</button>#}
{#        </div>#}
{#      </div><!-- /.modal-content -->#}
{#    </div><!-- /.modal-dialog -->#}
{#  </div><!-- /.modal -->#}

</div>

templates/profile.html
<div class="row"><br>
    <div class="col-md-4 table-bordered">
        <img src="{{ use.dp.url }}" style="width: 50%; height: auto" class="img-circle img-responsive"
             alt="{{ user }}"/>
        <h2>{{ user.first_name }} {{ user.last_name }}<br>
            <i style="font-size: 80%;color: #269abc">@{{ user.username }}</i>
        </h2>
    </div>
    <div class="col-md-8">
        <h4><i class="glyphicon glyphicon-home"></i> {{ user.city_town }}</h4>
        <h4><i class="glyphicon glyphicon-envelope"></i> {{ user.email }}</h4>
        <h4><i class="glyphicon glyphicon-phone"></i> {{ user.mobile }}</h4>
        </h2>

        <button class="btn btn-facebook" onclick="alert('Coming Soon!!')">
             <i class="fa fa-facebook"></i>&nbsp;
            Facebook
        </button>

        <button class="btn btn-twitter"  onclick="alert('Coming Soon!!')">
             <i class="fa fa-twitter"></i>&nbsp;
            Twitter
        </button>
        <button class="btn btn-github"  onclick="alert('Coming Soon!!')">
             <i class="fa fa-github"></i>&nbsp;
            GitHub
        </button>
        <br><br>
        <button class="btn btn-linkedin"  onclick="alert('Coming Soon!!')">
             <i class="fa fa-linkedin"></i>&nbsp;
            Linkedin
        </button>
        <button class="btn btn-instagram"  onclick="alert('Coming Soon!!')">
             <i class="fa fa-instagram"></i>&nbsp;
            Instagram
        </button>
         <button class="btn btn-google-plus"  onclick="alert('Coming Soon!!')">
             <i class="fa fa-google-plus"></i>&nbsp;
            Google+
        </button>
    </div>
</div>

templates/publish.html
<div class="form-group">
    <h3>
        Publish your Posts
    </h3>
    <form role="form" method="POST" action="{% url 'blog:publish' %}" enctype="multipart/form-data">

        {% csrf_token %}

        <div class="form-group">
            <input class="form-control" id="name" type="text" name="{{ form.name.name }}" placeholder="Name your foto" required />
        </div>

        <div class="form-group">
            <input class="form-control" type="file" name="{{ form.foto.name }}" required />
        </div>
        <div class="form-group"><input type="submit" class="btn btn-primary" value="Publish" /></div>
    </form>
</div>

templates/register.html
{% extends 'site_base.html' %}
{% block RightNav %}
<li><a href="{% url 'blog:login' %}"><span class="glyphicon glyphicon-log-in"></span> Login </a></li>
{% endblock %}
{% block content %}
{#    {% if form.errors %}#}
{#   <div class="alert alert-danger"> <p>Your username and password didn't match. Please try again. {{ form.errors }}</p></div>#}
{#{% endif %}#}

        <h2>Signup</h2>
    <form role="form" method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group">
      <input type="text" class="form-control" name="username" id="usr" placeholder="User Name" required/>
    </div>

        <div class="form-group">
      <input type="text" class="form-control" name="firstname" id="firstname" placeholder="First Name" required/>
    </div>

        <div class="form-group">
      <input type="text" class="form-control" name="lastname" id="lastname" placeholder="Last Name" required/>
    </div>

        <div class="form-group">
      <input type="text" class="form-control" name="mobile" id="mobile" placeholder="mobile" required/>
    </div>

        <div class="form-group">
      <input type="text" class="form-control" name="citytown" id="citytown" placeholder="City/Town" required/>
    </div>
<div class="form-group">
      <input type="file" class="file-upload" name="dp" id="dp" placeholder="DP" />
    </div>


            <div class="form-group">
      <input type="email" class="form-control" name="email" id="pwd" placeholder="Email ID" required/>
    </div>
      <div class="form-group">
      <input type="password" class="form-control" name="password" id="pwd" placeholder="Password" required/>
    </div>
<div class="form-group">
      <input type="password" class="form-control" name="password2" id="pwd" placeholder="Retype Password" required/>
    </div>

        <input class="btn btn-default" type="submit" value="Signup"/>
 </form>
{% endblock %}

templates/regsuccess.html
Registration Successful

templates/site_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Shokhila</title>
    <!-- Core CSS - Include with every page -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <link href="{% static '/static/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static '/static/css/main.css' %}" rel="stylesheet">
    <link href="{% static '/static/css/normalize.css' %}" rel="stylesheet">
    <link href="{% static '/static/css/mystyle.css' %}" rel="stylesheet">
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.0.0/bootstrap-social.css" rel="stylesheet" />

    {% block scripts %}
    {% endblock %}
    <script>
{#        $(document).ready(function () {#}
{#            $('a').click(function (event) {#}
{#                event.preventDefault();#}
{#            })#}
{##}
{#        });#}
    </script>
    <style>
        .navbar-brand {
  padding: 0px;

}
.navbar-brand>img {
  height: 100%;
  width: auto;

}
    </style>
</head>

<body style="padding-top: 70px">
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#"><img src="/static/images/black.png" class="img-responsive" /></a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                {% block LeftNav %}
                {% endblock %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
             {% block RightNav %}

             {% endblock %}
            </ul>
        </div>
    </div>
</nav>


<div class="container">

    {% block content %}
    {% endblock %}

    <!-- Core Scripts - Include with every page -->
    <script src="{% static 'js/jquery.min.js' %}"></script>

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
</div>
</body>

</html>

templates/update.html
{% if post %}
<form method="post" action="">
    <input type="text" name="title" value="{{ post.title }}" /> <br>
    <input name="code" type="textarea" value="{{ post.text }}"/><br>
    <input type="submit" id="but" name="submit" value="Update"/>
</form>
{% endif %}